# Generated by Django 5.2 on 2025-04-28 10:52

import django.db.models.deletion
import sa_modeltranslater.util_model
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sa_gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MINDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(editable=False, max_length=128, null=True, unique=True, verbose_name='Заголовок')),
                ('name_ru', models.CharField(max_length=128, unique=True, verbose_name='Заголовок')),
                ('name_kk', models.CharField(max_length=128, unique=True, verbose_name='Заголовок')),
                ('name_en', models.CharField(max_length=128, unique=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Тип мед. учреждения',
                'verbose_name_plural': 'Типы мед. учреждений',
            },
            bases=(models.Model, sa_modeltranslater.util_model.SaTransModel),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(editable=False, max_length=256, null=True, verbose_name='Процедура')),
                ('name_ru', models.CharField(max_length=256, verbose_name='Процедура')),
                ('name_kk', models.CharField(max_length=256, verbose_name='Процедура')),
                ('name_en', models.CharField(max_length=256, verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
            bases=(models.Model, sa_modeltranslater.util_model.SaTransModel),
        ),
        migrations.CreateModel(
            name='MIND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(editable=False, max_length=256, null=True, unique=True, verbose_name='Заголовок')),
                ('name_ru', models.CharField(max_length=256, unique=True, verbose_name='Заголовок')),
                ('name_kk', models.CharField(max_length=256, unique=True, verbose_name='Заголовок')),
                ('name_en', models.CharField(max_length=256, unique=True, verbose_name='Заголовок')),
                ('icon', models.ForeignKey(blank=True, help_text='Search occurs by internal name or by image name', null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_gallery.sagalleryimage', verbose_name='Иконка')),
                ('clinic_type', models.ManyToManyField(to='core.mindtype', verbose_name='Тип мед. учреждения')),
            ],
            options={
                'verbose_name': 'направление',
                'verbose_name_plural': 'направления',
            },
            bases=(sa_modeltranslater.util_model.SaUtilModel, models.Model, sa_modeltranslater.util_model.SaTransModel),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(editable=False, max_length=256, null=True, verbose_name='Названия процедуры')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='Названия процедуры')),
                ('name_kk', models.CharField(max_length=256, null=True, verbose_name='Названия процедуры')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Названия процедуры')),
                ('price_in_kzt', models.IntegerField(verbose_name='Цена в KZT')),
                ('mind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mind', verbose_name='направление')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.procedure', verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'Элемент прейскуранта',
                'verbose_name_plural': 'Прейскурант',
            },
            bases=(models.Model, sa_modeltranslater.util_model.SaTransModel),
        ),
    ]
