# Generated by Django 5.2 on 2025-04-28 11:56

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mind',
            name='desc',
            field=tinymce.models.HTMLField(editable=False, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='mind',
            name='desc_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='mind',
            name='desc_kk',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='mind',
            name='desc_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
    ]
