# Generated by Django 5.2 on 2025-04-28 10:52

import django.db.models.deletion
import sa_modeltranslater.util_model
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sa_gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('last_name', models.CharField(editable=False, max_length=72, null=True, verbose_name='Фамилия')),
                ('last_name_ru', models.CharField(max_length=72, verbose_name='Фамилия')),
                ('last_name_kk', models.CharField(max_length=72, verbose_name='Фамилия')),
                ('last_name_en', models.CharField(max_length=72, verbose_name='Фамилия')),
                ('first_name', models.CharField(editable=False, max_length=72, null=True, verbose_name='Имя')),
                ('first_name_ru', models.CharField(max_length=72, verbose_name='Имя')),
                ('first_name_kk', models.CharField(max_length=72, verbose_name='Имя')),
                ('first_name_en', models.CharField(max_length=72, verbose_name='Имя')),
                ('middle_name', models.CharField(editable=False, max_length=72, null=True, verbose_name='Отчество')),
                ('middle_name_ru', models.CharField(blank=True, max_length=72, null=True, verbose_name='Отчество')),
                ('middle_name_kk', models.CharField(blank=True, max_length=72, null=True, verbose_name='Отчество')),
                ('middle_name_en', models.CharField(blank=True, max_length=72, null=True, verbose_name='Отчество')),
                ('qualification', models.TextField(editable=False, null=True, verbose_name='Квалификация')),
                ('qualification_ru', models.TextField(verbose_name='Квалификация')),
                ('qualification_kk', models.TextField(verbose_name='Квалификация')),
                ('qualification_en', models.TextField(verbose_name='Квалификация')),
                ('med_total_exp', models.IntegerField(verbose_name='Общий стаж в медицине')),
                ('exp_in_the', models.IntegerField(verbose_name='На нынешнем месте работы с какого года')),
                ('job_title', models.CharField(editable=False, max_length=256, null=True, verbose_name='Должность')),
                ('job_title_ru', models.CharField(max_length=256, verbose_name='Должность')),
                ('job_title_kk', models.CharField(max_length=256, verbose_name='Должность')),
                ('job_title_en', models.CharField(max_length=256, verbose_name='Должность')),
                ('about_employee', tinymce.models.HTMLField(editable=False, null=True, verbose_name='О Враче')),
                ('about_employee_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='О Враче')),
                ('about_employee_kk', tinymce.models.HTMLField(blank=True, null=True, verbose_name='О Враче')),
                ('about_employee_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='О Враче')),
                ('mind', models.ManyToManyField(to='core.mind', verbose_name='направление')),
                ('photo', models.ForeignKey(blank=True, help_text='Search occurs by internal name or by image name', null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_gallery.sagalleryimage', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Врачь',
                'verbose_name_plural': 'Врачи',
                'abstract': False,
            },
            bases=(models.Model, sa_modeltranslater.util_model.SaTransModel),
        ),
    ]
