# Generated by Django 5.2 on 2025-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mind_desc_mind_desc_en_mind_desc_kk_mind_desc_ru'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mind',
            field=models.ManyToManyField(blank=True, to='core.mind', verbose_name='направление'),
        ),
    ]
