# Generated by Django 5.2 on 2025-04-28 10:52

import sa_gallery.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.ImageField(upload_to='gallery/originals/', validators=[sa_gallery.validators.ImageAndSvg.validate], verbose_name='Image link')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
