# Generated by Django 5.2 on 2025-04-28 10:52

import django.db.models.deletion
import sa_modeltranslater.util_model
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sa_gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('seo_name', models.CharField(max_length=428, null=True, verbose_name='SEO названия')),
                ('title', models.CharField(editable=False, max_length=256, null=True, unique=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=256, unique=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=256, unique=True, verbose_name='Заголовок')),
                ('desc', tinymce.models.HTMLField(editable=False, null=True, verbose_name='Новость')),
                ('desc_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Новость')),
                ('desc_kk', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Новость')),
                ('desc_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Новость')),
                ('small_desc', models.TextField(editable=False, null=True, verbose_name='Краткий подзаголовок новости')),
                ('small_desc_ru', models.TextField(blank=True, null=True, verbose_name='Краткий подзаголовок новости')),
                ('small_desc_kk', models.TextField(blank=True, null=True, verbose_name='Краткий подзаголовок новости')),
                ('small_desc_en', models.TextField(blank=True, null=True, verbose_name='Краткий подзаголовок новости')),
                ('created_at_ed', models.DateField(verbose_name='Дата создания')),
                ('title_image', models.ForeignKey(blank=True, help_text='Search occurs by internal name or by image name', null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_gallery.sagalleryimage', verbose_name='Главное изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'abstract': False,
            },
            bases=(models.Model, sa_modeltranslater.util_model.SaTransModel),
        ),
    ]
