# Generated by Django 5.2 on 2025-04-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at_ed', '-id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
